---

#
# This file is part of the `src-run/augustus-reflection-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
#

sudo     : false
language : php
php      : [ 7.1, 7.2, nightly ]

git:
  depth : 3

env:
  global:
    - secure : atKRJy12p0TP8UVYpWk6BIK3eHbmw9uvMFGfNOuuFzJs2HI4Ai+C5IYPrHiv94QH/qWr7jvQMjiWovmD/uyECGDLolbe8rOVP1GSclZAreETpBTnVnTV48Tm8eu0wUwHIMXtFS6v36etM4cxjx6wRRJaRQmAdUWOQwAFCL3OWQk7/Tl2KEcbqNMv/J+sau3i7Ra63GTJMvUgDBV9FImxPZ+LTyxJLPELk0hhONJJqwIz4pzyi1Cjl44TTco10rdcf5zeQcfuwKTvbQHQwnQ+IpVwligvksWgAogkqLDW4pECSHl5HvkoYOiJTeyE0KY2dABu9Nnq8jVf+ySNi+y2vXOgNGHHIr4HAPW0rUwQ3mAiFuSUy0TvgaFWrR7wtlFjLpKk/krg+QjowZz6N1CMjOqa7Ok19avD7+6XywcNGi0li4LKb0Vl9PUVZF7OQ2sMaToUCTu+63lDdDChubdkubonrDHeA2QCRa7iKQ4sxou+qOqviDWN/n0avDqbzfC1d2esyvT6FBZ9VSm8++CoIIbxIA9vh82gXf9HOT9iLvrDxlLS1R8LQHyWl3W6+3f7xdB3l7f/WzGcIberxRgRzyTh6Sv4ZXimoe4b6RFBW2zu5QLecNVip6U2H0xFmt9D0V2WKOFAaHRJUQMvfcA1mHPz9OKVQHcfjjUj+6J2bRc=

install :
  - bash .bldr/bldr -b up

script :
  - bin/simple-phpunit || bin/phpunit

after_script :
  - bash .bldr/bldr -b down

...
